apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9
        ports:
        - containerPort: 5672  # RabbitMQ port
        - containerPort: 15672 # Management UI port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: myuser  # RabbitMQ username
        - name: RABBITMQ_DEFAULT_PASS
          value: mypassword  # RabbitMQ password

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: management
      port: 15672
      targetPort: 15672
      nodePort: 30002
  type: NodePort
